name: Terraform destroy

on:
  workflow_dispatch:

jobs:
  destroy:
    name: "Terraform-Destroy"
    runs-on: ubuntu-latest
    env:
      working-directory: ./Modulo
      name:  h.web1
      owner: himanshi.soni@cloudeq.com
      AWS_REGION: ap-south-1

    steps:
  
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id :  ${{ secrets.ACCESS_KEY}}
          aws-secret-access-key : ${{ secrets.SECRET_ACCESS_KEY }}
          aws-session-token :     ${{ secrets.SESSION_TOKEN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Destroying infrastructure with Terraform
        working-directory: ${{env.working-directory}}
        run: |
          terraform init
          terraform destroy -var name="${{env.name}}" -var owner="${{env.owner}}"  -auto-approve
